swagger: "2.0"
info:
  title: "Mechanic Shop Management API"
  description: "API documentation for the Mechanic Shop Management System"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
paths:
  /customers:
    $ref: "./customer.yaml#/paths/~1customers"
  /customers/login:
    $ref: "./customer.yaml#/paths/~1customers~1login"
  /customers/{id}:
    $ref: "./customer.yaml#/paths/~1customers~1{id}"
  /mechanics:
    $ref: "./mechanic.yaml#/paths/~1mechanics"
  /mechanics/{id}:
    $ref: "./mechanic.yaml#/paths/~1mechanics~1{id}"
  # /serviceTickets:
  #   $ref: "./serviceTickets.yaml#/paths/~1serviceTickets"
  # /inventory:
  #   $ref: "./inventory.yaml#/paths/~1inventory"
